"""PDF renderer using WeasyPrint and Jinja2."""

import logging
from io import BytesIO
from pathlib import Path

from jinja2 import Environment, FileSystemLoader
from weasyprint import CSS, HTML

from app.models.schemas import GeneratedReport

logger = logging.getLogger(__name__)

# Default template directory
TEMPLATES_DIR = Path(__file__).parent.parent / "templates"


class PDFRenderer:
    """Renders reports as PDF documents using HTML templates."""

    def __init__(self, templates_dir: Path | None = None):
        """
        Initialize PDF renderer with templates.

        Args:
            templates_dir: Optional custom templates directory
        """
        self.templates_dir = templates_dir or TEMPLATES_DIR

        # Ensure templates directory exists
        self.templates_dir.mkdir(parents=True, exist_ok=True)

        # Create default templates if they don't exist
        self._ensure_templates()

        # Initialize Jinja2 environment
        self.env = Environment(
            loader=FileSystemLoader(str(self.templates_dir)),
            autoescape=True,
        )

    def _ensure_templates(self) -> None:
        """Create default templates if they don't exist."""
        template_path = self.templates_dir / "report_base.html"
        css_path = self.templates_dir / "styles.css"

        if not template_path.exists():
            template_path.write_text(DEFAULT_HTML_TEMPLATE)

        if not css_path.exists():
            css_path.write_text(DEFAULT_CSS)

    def render(self, report: GeneratedReport) -> BytesIO:
        """
        Render a report to PDF.

        Args:
            report: Generated report content

        Returns:
            BytesIO containing PDF data
        """
        try:
            # Load and render template
            template = self.env.get_template("report_base.html")
            html_content = template.render(report=report)

            # Load CSS
            css_path = self.templates_dir / "styles.css"
            css = CSS(filename=str(css_path)) if css_path.exists() else None

            # Generate PDF
            html = HTML(string=html_content, base_url=str(self.templates_dir))
            pdf_bytes = html.write_pdf(stylesheets=[css] if css else None)

            output = BytesIO(pdf_bytes)
            output.seek(0)
            return output

        except Exception as e:
            logger.error(f"PDF rendering failed: {e}")
            raise


# Default HTML template
DEFAULT_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ report.title }}</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header class="report-header">
        <h1>{{ report.title }}</h1>
    </header>

    <main>
        <section class="executive-summary">
            <h2>Executive Summary</h2>
            <div class="summary-content">
                {{ report.executive_summary | replace('\\n', '<br>') | safe }}
            </div>
        </section>

        {% for section in report.sections %}
        <section class="report-section">
            <h2>{{ section.title }}</h2>
            <div class="section-content">
                {{ section.content | replace('\\n', '<br>') | safe }}
            </div>

            {% for subsection in section.subsections %}
            <div class="subsection">
                <h3>{{ subsection.title }}</h3>
                <div class="subsection-content">
                    {{ subsection.content | replace('\\n', '<br>') | safe }}
                </div>
            </div>
            {% endfor %}
        </section>
        {% endfor %}

        <section class="key-findings">
            <h2>Key Findings</h2>
            <ul>
                {% for finding in report.key_findings %}
                <li>{{ finding }}</li>
                {% endfor %}
            </ul>
        </section>

        <section class="recommendations">
            <h2>Recommendations</h2>
            <ul>
                {% for rec in report.recommendations %}
                <li>{{ rec }}</li>
                {% endfor %}
            </ul>
        </section>

        {% if report.sources %}
        <section class="sources">
            <h2>Sources</h2>
            <ul>
                {% for source in report.sources %}
                <li>{{ source }}</li>
                {% endfor %}
            </ul>
        </section>
        {% endif %}
    </main>

    <footer>
        <p>Generated by Research Report Generator</p>
    </footer>
</body>
</html>
"""

# Default CSS
DEFAULT_CSS = """/* Report PDF Styles */
@page {
    size: A4;
    margin: 2cm;
    @bottom-center {
        content: counter(page);
        font-size: 10pt;
        color: #666;
    }
}

* {
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #333;
    max-width: 100%;
}

.report-header {
    text-align: center;
    margin-bottom: 2cm;
    padding-bottom: 1cm;
    border-bottom: 3px solid #2563eb;
}

.report-header h1 {
    font-size: 24pt;
    color: #1a1a1a;
    margin: 0;
    font-weight: 600;
}

h2 {
    font-size: 16pt;
    color: #2563eb;
    margin-top: 1.5cm;
    margin-bottom: 0.5cm;
    padding-bottom: 0.3cm;
    border-bottom: 1px solid #e5e7eb;
}

h3 {
    font-size: 13pt;
    color: #374151;
    margin-top: 1cm;
    margin-bottom: 0.3cm;
}

.executive-summary {
    background-color: #f8fafc;
    padding: 1cm;
    border-radius: 0.3cm;
    margin-bottom: 1cm;
}

.executive-summary h2 {
    margin-top: 0;
    color: #1e40af;
}

.summary-content {
    font-size: 11pt;
}

.report-section {
    page-break-inside: avoid;
}

.section-content,
.subsection-content {
    text-align: justify;
    margin-bottom: 0.5cm;
}

.subsection {
    margin-left: 0.5cm;
    padding-left: 0.5cm;
    border-left: 2px solid #e5e7eb;
}

.key-findings,
.recommendations {
    background-color: #f0f9ff;
    padding: 1cm;
    border-radius: 0.3cm;
    margin-top: 1cm;
}

.key-findings h2 {
    color: #0369a1;
    margin-top: 0;
}

.recommendations h2 {
    color: #047857;
    margin-top: 0;
}

ul {
    margin: 0;
    padding-left: 1cm;
}

li {
    margin-bottom: 0.3cm;
}

.key-findings li::marker {
    color: #0369a1;
}

.recommendations li::marker {
    color: #047857;
}

.sources {
    margin-top: 1cm;
    padding-top: 0.5cm;
    border-top: 1px solid #e5e7eb;
}

.sources h2 {
    font-size: 12pt;
    color: #6b7280;
}

.sources li {
    font-size: 10pt;
    color: #6b7280;
}

footer {
    margin-top: 2cm;
    text-align: center;
    font-size: 9pt;
    color: #9ca3af;
}
"""
